# This 2 functions works together to create a matrix object and calculate its inverse.  
# The result is then cached so that when is needed again it can be looked up in the cache rather than recomputed. 

# Example of use:
# m <- makeCacheMatrix(matrix(rnorm(4),2,2))  ## creates a matrix
# m$get()                                     ## gets the matrix
# cacheSolve(m)                               ## calculates the inverse  



# makeCacheMatrix creates a matrix object by taking "x" as an argument
# It contains functions to:
# 1. set the value of the matrix
# 2. get the value of the matrix
# 3. set the value of the inverse
# 4. get the value of the inverse

makeCacheMatrix <- function(x = matrix()) {
  i <- NULL
  set <- function(y) {
    x <<- y
    i<<- NULL
  }
  get <- function() x
  setsolve <- function(solve) i <<- solve
  getsolve <- function() i
  list(set = set, get = get,
       setsolve = setsolve ,
       getsolve = getsolve)
}


# cacheSolve computes the inverse of a squared matrix generated by the 
# above function.
# If the matrix was unchanged and the result was already calculated 
# it retrieves the cached inverse and print message "“getting cached data"”
# else it will show the result and cache it. 


cacheSolve <- function(x, ...) {
  i <- x$getsolve()
  if(!is.null(i)) {
    message("getting cached data")
    return(i)
  }
  data <- x$get()
  i <- solve(data, ...)
  x$setsolve(i)
  i
}